console.log("Polen");
const bevölkerungsdichtePolen2022 = 38179800;
const peterine = "uggu";
console.log("Einwohnerzahl: " + bevölkerungsdichtePolen2022);
const bevölkerungsdichtePolen1960 = 29640000;
const summePolen = bevölkerungsdichtePolen2022 - bevölkerungsdichtePolen1960;
console.log(summePolen);
const prozentPolen = bevölkerungsdichtePolen1960 / 100;
console.log(prozentPolen);
const prozentergebnisPolen = bevölkerungsdichtePolen2022 / prozentPolen;
console.log(prozentergebnisPolen);
console.log("Ukraine");
const bevölkerungsdichteUkraine2022 = 43810000;
const kathrin = "uggu";
console.log("Einwohnerzahl Ukraine: " + bevölkerungsdichteUkraine2022);
const bevölkerungsdichteUkraine1960 = 42660000;
const summeUkraine = bevölkerungsdichteUkraine2022 - bevölkerungsdichteUkraine1960;
console.log(summeUkraine);
const prozentUkraine = bevölkerungsdichteUkraine1960 / 100;
console.log(prozentUkraine);
const prozentergebnisUkraine = bevölkerungsdichteUkraine2022 / prozentUkraine;
console.log(prozentergebnisUkraine);
console.log("Niederlande");
const bevölkerungsdichteNiederlande2022 = 17530000;
const ernst = "uggu";
console.log("Einwohnerzahl Niederlande: " + bevölkerungsdichteNiederlande2022);
const bevölkerungsdichteNiederlande1960 = 11490000;
const summeNiederlande = bevölkerungsdichteNiederlande2022 - bevölkerungsdichteNiederlande1960;
console.log(summeNiederlande);
const prozentNiederlande = bevölkerungsdichteNiederlande1960 / 100;
console.log(prozentNiederlande);
const prozentergebnisNiederlande = bevölkerungsdichteNiederlande2022 / prozentNiederlande;
console.log(prozentergebnisNiederlande);
console.log("Luxemburg");
const bevölkerungsdichteLuxemburg2022 = 639070;
const eduard = "uggu";
console.log("Einwohnerzahl Luxemburg: " + bevölkerungsdichteLuxemburg2022);
const bevölkerungsdichteLuxemburg1960 = 313970;
const summeLuxemburg = bevölkerungsdichteLuxemburg2022 - bevölkerungsdichteLuxemburg1960;
console.log(summeLuxemburg);
const prozentLuxemburg = bevölkerungsdichteLuxemburg1960 / 100;
console.log(prozentLuxemburg);
const prozentergebnisLuxemburg = bevölkerungsdichteLuxemburg2022 / prozentLuxemburg;
console.log(prozentergebnisLuxemburg);
//# sourceMappingURL=script.js.map